name: Aux Records
favicon: null
layout_spectrum: 0.12926865625195205
typography_spectrum: 0.603752282448113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5490139711182564
  lightness: 0.8385823690332472
  saturation: 0.6992311202920973
  rhythmicContrast: 0.14477442810311913
purpose: []
